import "./globals.css";

import { Jost } from "next/font/google";

import { Header } from "@/components/Header";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "David Shubov",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={jost.className}>
      <body>
        <div className="pageContainer">
          <main className="mainContent">
            <Header />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
