import "./globals.css";

import { Inter } from "next/font/google";

import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "David Shubov",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <div className="pageContainer">
          <main className="mainContent">
            <Header />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
